<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="3">

  <testsuite name="miningGold"
    errors="1" failures="0" hostname="" id="" package="miningGold" skipped="2"
    tests="3" time="0.01100" timestamp="Tue, 25 Dec 2018 04:08:20 GMT">
  
    <testcase name="Sign In" classname="miningGold" time="0.01100" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Mining Gold / Sign In]:

  ReferenceError: username is not defined
    at Object.Sign In (C:\Users\Bracken\Desktop\DevMtn\yeOldProspector\tests\miningGold.js:18:45)
    at Module.call (C:\Users\Bracken\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\Bracken\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\Bracken\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at C:\Users\Bracken\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Users\Bracken\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\Bracken\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\Bracken\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\Bracken\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    </system-err>
  

  
    
    <testcase
      name="Signed In" classname="miningGold">
      <skipped />
    </testcase>
    
    <testcase
      name="Bing Search" classname="miningGold">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
